
version: '2'

services:
  greenchair:
    image: greenchair:latest
    build:
      context: .
      dockerfile: dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_USE_POLLING_FILE_WATCHER=1      
    volumes:
      - .:/app
    ports:
      - 5000:5000